version: '3.8'

services:
  # Banco de Dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: feedback-db
    environment:
      POSTGRES_USER: user_feedback
      POSTGRES_PASSWORD: password_feedback
      POSTGRES_DB: feedback_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # LocalStack (Simula AWS)
  localstack:
    image: localstack/localstack
    container_name: feedback-aws
    ports:
      - "4566:4566"            # Gateway
      - "4510-4559:4510-4559"  # Portas de serviços
    environment:
      - DEBUG=1
      # IMPORTANTE: Definir região ajuda a evitar erros de client
      - AWS_DEFAULT_REGION=us-east-1
      # IMPORTANTE: Não defina DATA_DIR aqui nas versões novas!
    volumes:
      # CORREÇÃO 1: Caminho correto para persistência nas versões novas
      - "./localstack_data:/var/lib/localstack"
      # CORREÇÃO 2: Necessário para o LocalStack falar com o Docker
      - "/var/run/docker.sock:/var/run/docker.sock"
      # Script de inicialização (se você criou a pasta scripts)
      - "./scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"

volumes:
  postgres_data: