services:
  # Banco de Dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: feedback-db
    environment:
      POSTGRES_USER: user_feedback
      POSTGRES_PASSWORD: password_feedback
      POSTGRES_DB: feedback_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # LocalStack (Simula AWS)
  localstack:
    image: localstack/localstack
    container_name: feedback-aws
    ports:
      - "4566:4566"            # Gateway
      - "4510-4559:4510-4559"  # Portas de servi√ßos
    environment:
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres_data: