spring:
  application:
    name: feedback-notification
  main:
    web-application-type: none

  cloud:
    function:
      definition: sendNotification

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

cloud:
  aws:
    region:
      static: ${AWS_REGION:}
    ses:
      endpoint: ${AWS_SES_ENDPOINT:}

app:
  ses:
    from-email: ${SES_FROM_EMAIL:}

aws:
  ses:
    sender-email: ${SES_FROM_EMAIL:}
    recipient-email: ${SES_RECIPIENT_EMAIL:}
    enabled: ${AWS_SES_ENABLED:true}

logging:
  level:
    root: INFO
    br.com.postech: INFO
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
