spring:
  application:
    name: feedback-notification
  cloud:
    function:
      definition: processNotification
    aws:
      region:
        static: us-east-2
      credentials:
        access-key: test
        secret-key: test
      endpoint: http://localhost:4566 # Aponta para o LocalStack

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

aws:
  ses:
    sender-email: noreply@feedbackplatform.com
    recipient-email: admin@feedbackplatform.com
    enabled: false  # Desabilitado para testes sem LocalStack
