spring:
  application:
    name: feedback-analysis
  cloud:
    function:
      definition: analyzeFeedback
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      endpoint: http://localhost:4566 # Aponta para o LocalStack

aws:
  sqs:
    queue-name: feedback-analysis-queue
  sns:
    topic:
      arn: arn:aws:sns:us-east-1:000000000000:feedback-notification-topic