spring:
  application:
    name: feedback-analysis
  main:
    web-application-type: none

  cloud:
    function:
      definition: analyzeFeedback
    aws:
      region:
        static: ${AWS_REGION:}
      sns:
        endpoint: ${AWS_SNS_ENDPOINT:}

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

app:
  sqs:
    queue-name: ${SQS_QUEUE_NAME:}
  sns:
    topic-arn: ${SNS_TOPIC_ARN:}

logging:
  level:
    root: INFO
    br.com.postech: INFO
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"