spring:
  application:
    name: feedback-analysis
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      endpoint: http://localhost:4566 # LocalStack

# Listener para rodar no local
cloud:
  aws:
    sqs:
      listener:
        auto-startup: true
        wait-time-out: 5s # Polling r√°pido para teste

aws:
  sqs:
    queue-name: feedback-analysis-queue
  sns:
    topic:
      arn: arn:aws:sns:us-east-1:000000000000:feedback-notification-topic