spring:
  application:
    name: feedback-ingestion
  main:
    web-application-type: none

  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 0
      connection-timeout: 10000
      initialization-fail-timeout: 0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    open-in-view: false

aws:
  region: ${AWS_REGION:}
  endpoint: ${AWS_ENDPOINT:}
  sqs:
    queue-name: ${SQS_QUEUE_NAME:}

app:
  sqs:
    queue-url: ${SQS_QUEUE_URL:}

logging:
  level:
    root: INFO
    br.com.postech: INFO
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
