spring:
  application:
    name: feedback-ingestion
  datasource:
    url: jdbc:postgresql://localhost:5439/feedback_db
    username: user_feedback
    password: password_feedback
  jpa:
    hibernate:
      ddl-auto: create-drop

aws:
  region: us-east-2
  endpoint: http://localhost:4566
  access-key: test
  secret-key: test
  sqs:
    queue-name: feedback-analysis-queue