spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    # A URL deve vir da variável de ambiente definida no Lambda Configuration
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 0
      connection-timeout: 10000
      initialization-fail-timeout: 0

# Configuração AWS
aws:
  region: us-east-2
  # Em PROD, endpoint deve ser vazio ou null para usar o padrão da AWS
  endpoint: ""
  # Não definimos access-key/secret-key aqui para forçar o uso da IAM Role

# Configuração da Aplicação
app:
  sqs:
    # URL completa da fila. Se a variável de ambiente não existir, usa um valor dummy para não quebrar o startup
    queue-url: ${SQS_QUEUE_URL:https://sqs.us-east-2.amazonaws.com/990227772490/feedback-analysis-queue}

logging:
  level:
    root: INFO
    br.com.postech: INFO