spring:
  application:
    name: feedback-ingestion
  datasource:
    url: jdbc:postgresql://localhost:5439/feedback_db
    username: user_feedback
    password: password_feedback
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        accessKey: test
        secretKey: test
      sqs:
        endpoint: http://localhost:4566
  jpa:
    hibernate:
      ddl-auto: create-drop