spring:
  application:
    name: feedback-ingestion
  datasource:
    url: jdbc:postgresql://localhost:5439/feedback_db
    username: user_feedback
    password: password_feedback
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      endpoint: http://localhost:4566 # Aponta para o LocalStack
  jpa:
    hibernate:
      ddl-auto: create-drop

aws:
  sqs:
    queue-name: feedback-analysis-queue