spring:
  application:
    name: feedback-ingestion
  datasource:
    url: jdbc:postgresql://localhost:5432/feedback_db
    username: user_feedback
    password: password_feedback

aws:
  region: us-east-1
  endpoint: http://localhost:4566
  access-key: test
  secret-key: test
  sqs:
    queue-name: feedback-analysis-queue