spring:
  application:
    name: feedback-reporting
  main:
    web-application-type: none

  cloud:
    function:
      definition: generateReport

  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    open-in-view: false

cloud:
  aws:
    region:
      static: ${AWS_REGION:}
    s3:
      endpoint: ${AWS_S3_ENDPOINT:}
    sns:
      endpoint: ${AWS_SNS_ENDPOINT:}

aws:
  region: ${AWS_REGION:}
  s3:
    bucket-name: ${S3_BUCKET_NAME:}
  sns:
    topic-arn: ${SNS_TOPIC_ARN:}

reporting:
  format: ${REPORT_FORMAT:csv}

logging:
  level:
    root: INFO
    br.com.postech: INFO
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
