spring:
  application:
    name: feedback-reporting
  main:
    web-application-type: servlet
  cloud:
    function:
      definition: generateReport
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:feedback_db}
    username: ${DB_USER:user_feedback}
    password: ${DB_PASSWORD:password_feedback}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:8080}

# AWS Configuration
aws:
  region: ${AWS_REGION:us-east-2}
  endpoint: ${AWS_ENDPOINT:http://localhost:4566}
  access-key: ${AWS_ACCESS_KEY_ID:test}
  secret-key: ${AWS_SECRET_ACCESS_KEY:test}
  s3:
    bucket-name: ${REPORT_BUCKET_NAME:postech-feedback-reports}
  sns:
    topic-arn: ${SNS_TOPIC_ARN:arn:aws:sns:us-east-2:000000000000:feedback-notification-topic}

# Report Configuration
reporting:
  format: ${REPORT_FORMAT:json}

# Logging
logging:
  level:
    root: INFO
    br.com.postech.feedback: DEBUG
